// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoe4CPWwNViG4Vd1f-d9mMk-GLRUM-lqk',
    appId: '1:1023646961703:web:b4898974e6738605417e02',
    messagingSenderId: '1023646961703',
    projectId: 'salonde-c-fada9',
    authDomain: 'salonde-c-fada9.firebaseapp.com',
    storageBucket: 'salonde-c-fada9.appspot.com',
    measurementId: 'G-S4G16343KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1EjJ0mqSsbmw8qgTB9Qli1EJYuKS3CY',
    appId: '1:1023646961703:android:69d8a9b3b91315f8417e02',
    messagingSenderId: '1023646961703',
    projectId: 'salonde-c-fada9',
    storageBucket: 'salonde-c-fada9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVBU5i_Db_1CxURGMIP1Kne24FBMev3Q',
    appId: '1:1023646961703:ios:f9ca0d8e3ff5adad417e02',
    messagingSenderId: '1023646961703',
    projectId: 'salonde-c-fada9',
    storageBucket: 'salonde-c-fada9.appspot.com',
    iosClientId: '1023646961703-3jog8efsnocgulolphnpslbhvs5bhmim.apps.googleusercontent.com',
    iosBundleId: 'com.ruming.salondec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVBU5i_Db_1CxURGMIP1Kne24FBMev3Q',
    appId: '1:1023646961703:ios:3ec876cf226f36df417e02',
    messagingSenderId: '1023646961703',
    projectId: 'salonde-c-fada9',
    storageBucket: 'salonde-c-fada9.appspot.com',
    iosClientId: '1023646961703-v464k4l5f678vvdih25r317lpqv9uivd.apps.googleusercontent.com',
    iosBundleId: 'com.guruguru.salondc',
  );
}
